language: ruby
rvm:
- 2.2.0
- 2.3.0
- 2.4.0
script:
- bundle exec rspec spec
notifications:
  webhooks:
    secure: Z52QFyfZwrQbkfYfTexO/K+CiYtik4IskhUoLZHQctraIx32F78T63kJHaQcX2Glkmarw1Ak1FJwA6vjweNv0BHT9WUQEo1rHX7am79YNmmHrbdQwgrbdoh7fVSSnaJvL8+qfirxJEhSvT3n7tg0pEeyAT41WNa05ViETCRRZxY=
